name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for accurate blame info

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 20

      - name: Install Node dependencies
        run: npm ci

      - name: Run tests (optional, if coverage is generated)
        run: echo "Testing..."

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
